### ISSUE TITLE
Admin permissions not detected using Google OAuth

### ISSUE THREAD

**Issue by benthompsonhx** [looker-open-source/admin_power_pack#2]
We use Google OAuth to access Looker. Admin Power Pack does not pick up my admin privileges. I get the following message:

>Hi there!
This application helps Looker Administrators accomplish certain tasks more efficiently, so it requires Admin permissions.

>However, we weren't able to detect Admin permissions for your user account 🙁

>Please contact your Looker Administrator if you have any questions.

>If you do have Admin permissions and are seeing this page, please check the javascript console for errors.

>You are currently logged in as:

>{}

The console shows:

>TypeError: Cannot read properties of undefined (reading 'includes')
    at looker_admin_power_pack.js:35:310337
    at Array.filter (<anonymous>)
    at looker_admin_power_pack.js:35:310316

Is this a known problem?

Many thanks

Ben

**Comment by davidtamaki** [comment]
@benthompsonhx this looks like a dupe of https://github.com/looker-open-source/admin_power_pack/issues/1 which was fixed in the release [v1.0.3](https://github.com/looker-open-source/admin_power_pack/releases/tag/v1.0.3)

If you update the pack it should be resolved!

**Comment by benthompsonhx** [comment]
Many thanks, yes, this is resolved, I see the power pack again, logging in via Google.
